### ISSUE TITLE
Better process naming

### ISSUE THREAD

**Issue by igoldny** [sindresorhus/fkill-cli#18]
When i'm trying to kill my app node server, i'm looking for node and i get this:
<img width="235" alt="screen shot 2017-03-05 at 12 38 36 pm" src="https://cloud.githubusercontent.com/assets/480868/23586592/f3d119d2-01a0-11e7-8d41-dbeed9346cb1.png">

but how can i choose the correct one when all of them with the same name?

**Comment by coffeedoughnuts** [comment]
I submitted a PR to add this functionality here: #14 

If merged, it will allow the option of `fkill -v` or `fkill --verbose` so that you can filter by, and see, the fully command including arguments.

Not sure on the maintainers availability to review Pull Requests, but hopefully they'll get around to evaluating it soon.
